package P3401_3500.P3474_Lexicographically_Smallest_Generated_String;

public class Main {

    public static void main(String[] args) {
        Main solution = new Main();

        System.out.println(solution.generateString("TFTF", "ab"));  // ababa
        System.out.println(solution.generateString("TFTF", "abc")); // ""
        System.out.println(solution.generateString("F", "d"));      // a
        System.out.println(solution.generateString("FTFT", "dcaa")); // ""
    }

    public String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        int len = n + m - 1;

        char[] word = new char[len];

        //fill with '?'
        for (int i = 0; i < len; i++) {
            word[i] = '?';
        }

        // enforce 'T'
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    if (word[i + j] == '?' || word[i + j] == str2.charAt(j)) {
                        word[i + j] = str2.charAt(j);
                    } else {
                        return "";
                    }
                }
            }
        }

        // fill remaining positions
        for (int i = 0; i < len; i++) {
            if (word[i] == '?') {

                for (char c = 'a'; c <= 'z'; c++) {
                    word[i] = c;

                    if (isSafe(word, str1, str2, i)) {
                        break;
                    }
                }
            }
        }

        String result = new String(word);

        // final validation
        return isValid(result, str1, str2) ? result : "";
    }

    // check only affected windows
    private boolean isSafe(char[] word, String str1, String str2, int pos) {
        int n = str1.length();
        int m = str2.length();

        for (int i = Math.max(0, pos - m + 1); i <= Math.min(n - 1, pos); i++) {

            if (str1.charAt(i) == 'F') {
                boolean match = true;

                for (int j = 0; j < m; j++) {
                    if (word[i + j] == '?' || word[i + j] != str2.charAt(j)) {
                        match = false;
                        break;
                    }
                }

                if (match) return false;
            }
        }

        return true;
    }

    private boolean isValid(String word, String str1, String str2) {
        int n = str1.length();
        int m = str2.length();

        for (int i = 0; i < n; i++) {
            String sub = word.substring(i, i + m);

            if (str1.charAt(i) == 'T' && !sub.equals(str2)) return false;
            if (str1.charAt(i) == 'F' && sub.equals(str2)) return false;
        }

        return true;
    }

}

//Complexity:
// time: O((n+m) * m * 26)
// space: O(n + m)


//You are given two strings, str1 and str2, of lengths n and m, respectively.
//A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following
// conditions for each index 0 <= i <= n - 1:
//If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e.,
// word[i..(i + m - 1)] == str2.
//If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e.,
// word[i..(i + m - 1)] != str2.
//Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be
// generated, return an empty string "".

//Example 1:
//Input: str1 = "TFTF", str2 = "ab"
//Output: "ababa"
//Explanation:
//The table below represents the string "ababa"
//Index	    T/F	      Substring of length m
// 0	    'T'	      "ab"
// 1	    'F'	      "ba"
// 2	    'T'	      "ab"
// 3	    'F'	      "ba"
//The strings "ababa" and "ababb" can be generated by str1 and str2.
//
//Return "ababa" since it is the lexicographically smaller string.

//Example 2:
//Input: str1 = "TFTF", str2 = "abc"
//Output: ""
//Explanation:
//No string that satisfies the conditions can be generated.

//Example 3:
//Input: str1 = "F", str2 = "d"
//Output: "a"

//Constraints:
//1 <= n == str1.length <= 104
//1 <= m == str2.length <= 500
//str1 consists only of 'T' or 'F'.
//str2 consists only of lowercase English characters.
