package P301_400.P389_Find_the_Difference;

public class Main {

    public static void main(String[] args) {
        Main solution = new Main();
        String s1 = "abcd";
        String t1 = "abcde";
        System.out.println(solution.findTheDifference(s1, t1));
    }

    public char findTheDifference(String s, String t) {
        char[] fromS = s.toCharArray();
        char[] fromT = t.toCharArray();
        int sumS = 0;
        int sumT = 0;
        int result = 0;

        if (s.isEmpty()) {
            result = fromT[0];
        }

        for (int i = 0; i < fromT.length; i++) {
            sumT += fromT[i];
        }
        for (int j = 0; j < fromS.length; j++) {
            sumS += fromS[j];
        }

        result = sumT - sumS;

        return (char)result;
    }

}

//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

//Example 1:
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.

//Example 2:
//Input: s = "", t = "y"
//Output: "y"

//Constraints:
//0 <= s.length <= 1000
//t.length == s.length + 1
//s and t consist of lowercase English letters.
